In [1]:
import pandas as pd
import numpy as np
import matplotlib as plt
import seaborn as sns
from sklearn.impute import SimpleImputer

In [2]:
df = pd.read_csv("../data/raw/Churn_Modelling.csv")

In [3]:
df.head(5)

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,1,15634602,Hargrave,619,France,Female,42,2,0.00,1,1,1,101348.88,1
1,2,15647311,Hill,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0
2,3,15619304,Onio,502,France,Female,42,8,159660.80,3,1,0,113931.57,1
3,4,15701354,Boni,699,France,Female,39,1,0.00,2,0,0,93826.63,0
4,5,15737888,Mitchell,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0

In [4]:
df["Exited"].value_counts()

Exited
0    7963
1    2037
Name: count, dtype: int64

In [5]:
df["Exited"].value_counts(normalize=True) * 100

Exited
0    79.63
1    20.37
Name: proportion, dtype: float64

In [6]:
df.describe()

,RowNumber,CustomerId,CreditScore,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
count,10000.00000,1.000000e+04,10000.000000,10000.000000,10000.000000,10000.000000,10000.000000,10000.00000,10000.000000,10000.000000,10000.000000
mean,5000.50000,1.569094e+07,650.528800,38.921800,5.012800,76485.889288,1.530200,0.70550,0.515100,100090.239881,0.203700
std,2886.89568,7.193619e+04,96.653299,10.487806,2.892174,62397.405202,0.581654,0.45584,0.499797,57510.492818,0.402769
min,1.00000,1.556570e+07,350.000000,18.000000,0.000000,0.000000,1.000000,0.00000,0.000000,11.580000,0.000000
25%,2500.75000,1.562853e+07,584.000000,32.000000,3.000000,0.000000,1.000000,0.00000,0.000000,51002.110000,0.000000
50%,5000.50000,1.569074e+07,652.000000,37.000000,5.000000,97198.540000,1.000000,1.00000,1.000000,100193.915000,0.000000
75%,7500.25000,1.575323e+07,718.000000,44.000000,7.000000,127644.240000,2.000000,1.00000,1.000000,149388.247500,0.000000
max,10000.00000,1.581569e+07,850.000000,92.000000,10.000000,250898.090000,4.000000,1.00000,1.000000,199992.480000,1.000000

In [7]:
df.groupby("Geography")["Exited"].mean()

Geography
France     0.161548
Germany    0.324432
Spain      0.166734
Name: Exited, dtype: float64

In [8]:
df.groupby("Gender")["Exited"].mean()

Gender
Female    0.250715
Male      0.164559
Name: Exited, dtype: float64

In [9]:
df.groupby("Exited")["Age"].mean()

Exited
0    37.408389
1    44.837997
Name: Age, dtype: float64

In [10]:
df.groupby("Exited")[[
    "CreditScore",
    "Age",
    "Tenure",
    "Balance",
    "NumOfProducts",
    "EstimatedSalary"
]].mean()

,CreditScore,Age,Tenure,Balance,NumOfProducts,EstimatedSalary
Exited,,,,,,
0,651.853196,37.408389,5.033279,72745.296779,1.544267,99738.391772
1,645.351497,44.837997,4.932744,91108.539337,1.475209,101465.677531

In [11]:
df.groupby("HasCrCard")["Exited"].mean()

HasCrCard
0    0.208149
1    0.201843
Name: Exited, dtype: float64

In [12]:
df.groupby("IsActiveMember")["Exited"].mean()

IsActiveMember
0    0.268509
1    0.142691
Name: Exited, dtype: float64

In [13]:
df.groupby("NumOfProducts")["Exited"].mean()

NumOfProducts
1    0.277144
2    0.075817
3    0.827068
4    1.000000
Name: Exited, dtype: float64

In [14]:
df["NumOfProducts"].value_counts().sort_index()

NumOfProducts
1    5084
2    4590
3     266
4      60
Name: count, dtype: int64

In [15]:
df[
    [
        "CreditScore",
        "Age",
        "Tenure",
        "Balance",
        "NumOfProducts",
        "HasCrCard",
        "IsActiveMember",
        "EstimatedSalary",
        "Exited"
    ]
].corr()

,CreditScore,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
CreditScore,1.000000,-0.003965,0.000842,0.006268,0.012238,-0.005458,0.025651,-0.001384,-0.027094
Age,-0.003965,1.000000,-0.009997,0.028308,-0.030680,-0.011721,0.085472,-0.007201,0.285323
Tenure,0.000842,-0.009997,1.000000,-0.012254,0.013444,0.022583,-0.028362,0.007784,-0.014001
Balance,0.006268,0.028308,-0.012254,1.000000,-0.304180,-0.014858,-0.010084,0.012797,0.118533
NumOfProducts,0.012238,-0.030680,0.013444,-0.304180,1.000000,0.003183,0.009612,0.014204,-0.047820
HasCrCard,-0.005458,-0.011721,0.022583,-0.014858,0.003183,1.000000,-0.011866,-0.009933,-0.007138
IsActiveMember,0.025651,0.085472,-0.028362,-0.010084,0.009612,-0.011866,1.000000,-0.011421,-0.156128
EstimatedSalary,-0.001384,-0.007201,0.007784,0.012797,0.014204,-0.009933,-0.011421,1.000000,0.012097
Exited,-0.027094,0.285323,-0.014001,0.118533,-0.047820,-0.007138,-0.156128,0.012097,1.000000

In [16]:
X = df.drop(columns=["RowNumber", "CustomerId", "Surname", "Exited"])
y = df["Exited"]

In [17]:
X

,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary
0,619,France,Female,42,2,0.00,1,1,1,101348.88
1,608,Spain,Female,41,1,83807.86,1,0,1,112542.58
2,502,France,Female,42,8,159660.80,3,1,0,113931.57
3,699,France,Female,39,1,0.00,2,0,0,93826.63
4,850,Spain,Female,43,2,125510.82,1,1,1,79084.10
...,...,...,...,...,...,...,...,...,...,...
9995,771,France,Male,39,5,0.00,2,1,0,96270.64
9996,516,France,Male,35,10,57369.61,1,1,1,101699.77
9997,709,France,Female,36,7,0.00,1,0,1,42085.58
9998,772,Germany,Male,42,3,75075.31,2,1,0,92888.52
9999,792,France,Female,28,4,130142.79,1,1,0,38190.78

In [18]:
y

0       1
1       0
2       1
3       0
4       0
       ..
9995    0
9996    0
9997    1
9998    1
9999    0
Name: Exited, Length: 10000, dtype: int64

In [19]:
X.shape

(10000, 10)

In [20]:
y.shape

(10000,)

In [21]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X,y, test_size=0.20, random_state=42, stratify=y)

In [22]:
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import StandardScaler, OneHotEncoder
from sklearn.compose import ColumnTransformer

In [23]:
numeric_features = [
    "CreditScore",
    "Age",
    "Tenure",
    "Balance",
    "NumOfProducts",
    "HasCrCard",
    "IsActiveMember",
    "EstimatedSalary"
]

categorical_features = [
    "Geography",
    "Gender"
]

In [24]:
num_pipeline = Pipeline([('scaler', StandardScaler())])
cat_pipeline = Pipeline([('encoder', OneHotEncoder(handle_unknown='ignore'))])

In [25]:
preprocessor = ColumnTransformer([
    ('num', num_pipeline, numeric_features),
    ('cat', cat_pipeline, categorical_features)
])

In [26]:
X_train_processed = preprocessor.fit_transform(X_train)

In [27]:
X_test_processed = preprocessor.transform(X_test)

In [28]:
from sklearn.dummy import DummyClassifier
d_model = DummyClassifier(strategy='most_frequent')
d_model.fit(X_train, y_train)
y_d_pred = d_model.predict(X_test)
y_d_pred

array([0, 0, 0, ..., 0, 0, 0], shape=(2000,))

In [33]:
from sklearn.metrics import accuracy_score, confusion_matrix
accuracy_score(y_test, y_d_pred)

NameError: name 'y_d_pred' is not defined

In [31]:
confusion_matrix(y_test, y_d_pred)

array([[1593,    0],
       [ 407,    0]])

In [28]:
from sklearn.linear_model import LogisticRegression
logistic = LogisticRegression(max_iter=1000)
logistic.fit(X_train_processed, y_train)

LogisticRegression(max_iter=1000)

In [29]:
y_pred_logistic = logistic.predict(X_test_processed)

In [30]:
y_train

2151    1
8392    1
5006    0
4117    0
7182    0
       ..
4555    1
4644    0
8942    0
2935    0
6206    0
Name: Exited, Length: 8000, dtype: int64

In [31]:
from sklearn.metrics import accuracy_score
accuracy_score(y_test, y_pred_logistic)

0.808

In [34]:
from sklearn.metrics import confusion_matrix
confusion_matrix(y_test, y_pred_logistic)

array([[1540,   53],
       [ 331,   76]])

In [35]:
from sklearn.metrics import classification_report
print(classification_report(y_test, y_pred_logistic))

              precision    recall  f1-score   support

           0       0.82      0.97      0.89      1593
           1       0.59      0.19      0.28       407

    accuracy                           0.81      2000
   macro avg       0.71      0.58      0.59      2000
weighted avg       0.78      0.81      0.77      2000

In [36]:
y_prob_logistic = logistic.predict_proba(X_test_processed)[:, 1]
from sklearn.metrics import roc_auc_score
roc_auc_score(y_test, y_prob_logistic)

0.7747578086561138

In [37]:
tree_preprocessor = ColumnTransformer([
    ('num', 'passthrough', numeric_features),
    ('cat', cat_pipeline, categorical_features)
])

In [38]:
X_train_tree = tree_preprocessor.fit_transform(X_train)
X_test_tree = tree_preprocessor.transform(X_test)

In [39]:
X_train_tree.shape, X_test_tree.shape

((8000, 13), (2000, 13))

In [40]:
from sklearn.tree import DecisionTreeClassifier
tree_model = DecisionTreeClassifier(random_state=42)
tree_model.fit(X_train_tree, y_train)

DecisionTreeClassifier(random_state=42)

In [42]:
y_pred_tree = tree_model.predict(X_test_tree)

In [44]:
y_prob_tree = tree_model.predict_proba(X_test_tree)[:, 1]

In [45]:
from sklearn.metrics import accuracy_score,confusion_matrix,classification_report,roc_auc_score
print("Accuracy:", accuracy_score(y_test, y_pred_tree))
print("\nConfusion Matrix:")
print(confusion_matrix(y_test, y_pred_tree))
print("\nClassification Report:")
print(classification_report(y_test, y_pred_tree))
print("\nROC-AUC:", roc_auc_score(y_test, y_prob_tree))

Accuracy: 0.7955

Confusion Matrix:
[[1375  218]
 [ 191  216]]

Classification Report:
              precision    recall  f1-score   support

           0       0.88      0.86      0.87      1593
           1       0.50      0.53      0.51       407

    accuracy                           0.80      2000
   macro avg       0.69      0.70      0.69      2000
weighted avg       0.80      0.80      0.80      2000


ROC-AUC: 0.6969319087963155

In [46]:
from sklearn.ensemble import RandomForestClassifier
rf_model = RandomForestClassifier(random_state=42)
rf_model.fit(X_train_tree, y_train)

RandomForestClassifier(random_state=42)

In [47]:
y_pred_rf = rf_model.predict(X_test_tree)

In [48]:
y_prob_rf = rf_model.predict_proba(X_test_tree)[:, 1]

In [49]:
print("Accuracy:", accuracy_score(y_test, y_pred_rf))
print("\nConfusion Matrix:")
print(confusion_matrix(y_test, y_pred_rf))
print("\nClassification Report:")
print(classification_report(y_test, y_pred_rf))
print("\nROC-AUC:", roc_auc_score(y_test, y_prob_rf))

Accuracy: 0.8585

Confusion Matrix:
[[1538   55]
 [ 228  179]]

Classification Report:
              precision    recall  f1-score   support

           0       0.87      0.97      0.92      1593
           1       0.76      0.44      0.56       407

    accuracy                           0.86      2000
   macro avg       0.82      0.70      0.74      2000
weighted avg       0.85      0.86      0.84      2000


ROC-AUC: 0.8464550837432193

In [64]:
from sklearn.ensemble import GradientBoostingClassifier
gb_model = GradientBoostingClassifier(random_state=42)
gb_model.fit(X_train_tree, y_train)

GradientBoostingClassifier(random_state=42)

In [65]:
y_pred_gb = gb_model.predict(X_test_tree)

In [52]:
print("Accuracy:", accuracy_score(y_test, y_pred_gb))
print("\nConfusion Matrix:")
print(confusion_matrix(y_test, y_pred_gb))
print("\nClassification Report:")
print(classification_report(y_test, y_pred_gb))

Accuracy: 0.869

Confusion Matrix:
[[1537   56]
 [ 206  201]]

Classification Report:
              precision    recall  f1-score   support

           0       0.88      0.96      0.92      1593
           1       0.78      0.49      0.61       407

    accuracy                           0.87      2000
   macro avg       0.83      0.73      0.76      2000
weighted avg       0.86      0.87      0.86      2000

In [54]:
gb_model = GradientBoostingClassifier(random_state=42)

In [55]:
param_grid_gb = {
    "n_estimators": [50, 100, 150],
    "learning_rate": [0.05, 0.1, 0.2],
    "max_depth": [2, 3, 4]
}

In [56]:
from sklearn.model_selection import GridSearchCV
gb_grid_search = GridSearchCV(estimator=gb_model,param_grid=param_grid_gb,scoring='f1',cv=5,n_jobs=-1)
gb_grid_search.fit(X_train_tree, y_train)

GridSearchCV(cv=5, estimator=GradientBoostingClassifier(random_state=42),
             n_jobs=-1,
             param_grid={'learning_rate': [0.05, 0.1, 0.2],
                         'max_depth': [2, 3, 4],
                         'n_estimators': [50, 100, 150]},
             scoring='f1')

In [57]:
gb_grid_search.best_params_

{'learning_rate': 0.2, 'max_depth': 4, 'n_estimators': 150}

In [58]:
gb_grid_search.best_score_

np.float64(0.5882619165213563)

In [59]:
best_gb_model = gb_grid_search.best_estimator_
y_pred_gb_tuned = best_gb_model.predict(X_test_tree)

In [62]:
print("Accuracy:", accuracy_score(y_test, y_pred_gb_tuned))
print("\nConfusion Matrix:")
print(confusion_matrix(y_test, y_pred_gb_tuned))
print("\nClassification Report:")
print(classification_report(y_test, y_pred_gb_tuned))

Accuracy: 0.8605

Confusion Matrix:
[[1524   69]
 [ 210  197]]

Classification Report:
              precision    recall  f1-score   support

           0       0.88      0.96      0.92      1593
           1       0.74      0.48      0.59       407

    accuracy                           0.86      2000
   macro avg       0.81      0.72      0.75      2000
weighted avg       0.85      0.86      0.85      2000

In [66]:
y_prob_gb = gb_model.predict_proba(X_test_tree)[:, 1]

In [67]:
threshold = 0.40
y_pred_gb_40 = (y_prob_gb >= threshold).astype(int)

In [68]:
print("Accuracy:", accuracy_score(y_test, y_pred_gb_40))
print("\nConfusion Matrix:")
print(confusion_matrix(y_test, y_pred_gb_40))
print("\nClassification Report:")
print(classification_report(y_test, y_pred_gb_40))

Accuracy: 0.8635

Confusion Matrix:
[[1503   90]
 [ 183  224]]

Classification Report:
              precision    recall  f1-score   support

           0       0.89      0.94      0.92      1593
           1       0.71      0.55      0.62       407

    accuracy                           0.86      2000
   macro avg       0.80      0.75      0.77      2000
weighted avg       0.86      0.86      0.86      2000

In [69]:
import numpy as np
from sklearn.metrics import f1_score, precision_score, recall_score, accuracy_score

In [71]:
thresholds = np.arange(0.20, 0.71, 0.05)
thresholds

array([0.2 , 0.25, 0.3 , 0.35, 0.4 , 0.45, 0.5 , 0.55, 0.6 , 0.65, 0.7 ])

In [73]:
results = []
for thres in thresholds:
    y_new_pred = (y_prob_gb >= thres).astype(int)
    results.append({
        "threshold": thres,
        "accuracy": accuracy_score(y_test, y_new_pred),
        "precision": precision_score(y_test, y_new_pred),
        "recall": recall_score(y_test, y_new_pred),
        "f1": f1_score(y_test, y_new_pred)
    })
results

[{'threshold': np.float64(0.2),
  'accuracy': 0.8035,
  'precision': 0.5114754098360655,
  'recall': 0.7665847665847666,
  'f1': 0.6135693215339233},
 {'threshold': np.float64(0.25),
  'accuracy': 0.831,
  'precision': 0.5691382765531062,
  'recall': 0.6977886977886978,
  'f1': 0.6269315673289183},
 {'threshold': np.float64(0.3),
  'accuracy': 0.85,
  'precision': 0.6276849642004774,
  'recall': 0.6461916461916462,
  'f1': 0.6368038740920097},
 {'threshold': np.float64(0.35),
  'accuracy': 0.8565,
  'precision': 0.6621621621621622,
  'recall': 0.601965601965602,
  'f1': 0.6306306306306306},
 {'threshold': np.float64(0.39999999999999997),
  'accuracy': 0.8635,
  'precision': 0.7133757961783439,
  'recall': 0.5503685503685504,
  'f1': 0.6213592233009708},
 {'threshold': np.float64(0.44999999999999996),
  'accuracy': 0.8655,
  'precision': 0.7412587412587412,
  'recall': 0.5208845208845209,
  'f1': 0.6118326118326118},
 {'threshold': np.float64(0.49999999999999994),
  'accuracy': 0.869,
  'precision': 0.7821011673151751,
  'recall': 0.49385749385749383,
  'f1': 0.6054216867469879},
 {'threshold': np.float64(0.5499999999999999),
  'accuracy': 0.865,
  'precision': 0.815668202764977,
  'recall': 0.4348894348894349,
  'f1': 0.5673076923076923},
 {'threshold': np.float64(0.5999999999999999),
  'accuracy': 0.8655,
  'precision': 0.8709677419354839,
  'recall': 0.39803439803439805,
  'f1': 0.5463743676222597},
 {'threshold': np.float64(0.6499999999999999),
  'accuracy': 0.8615,
  'precision': 0.8869047619047619,
  'recall': 0.36609336609336607,
  'f1': 0.5182608695652174},
 {'threshold': np.float64(0.7),
  'accuracy': 0.855,
  'precision': 0.9090909090909091,
  'recall': 0.3194103194103194,
  'f1': 0.4727272727272727}]

In [74]:
best_result = max(results, key=lambda x: x["f1"])
best_result

{'threshold': np.float64(0.3),
 'accuracy': 0.85,
 'precision': 0.6276849642004774,
 'recall': 0.6461916461916462,
 'f1': 0.6368038740920097}

In [75]:
gb_model = GradientBoostingClassifier(random_state=42)

In [76]:
from sklearn.model_selection import cross_val_predict
y_prob_cv = cross_val_predict(
    gb_model,
    X_train_tree,
    y_train,
    cv=5,
    method="predict_proba",
    n_jobs=-1
)[:, 1]

In [77]:
y_prob_cv

array([0.90249937, 0.20145757, 0.17600032, ..., 0.05483232, 0.05608906,
       0.37467079], shape=(8000,))

In [78]:
np.arange(0.20, 0.71, 0.05)

array([0.2 , 0.25, 0.3 , 0.35, 0.4 , 0.45, 0.5 , 0.55, 0.6 , 0.65, 0.7 ])

In [79]:
thresholds = np.arange(0.20, 0.71, 0.05)
cv_threshold_results = []
for t in thresholds:
    y_pred = (y_prob_cv >= t).astype(int)
    cv_threshold_results.append({
        "threshold": t,
        "accuracy": accuracy_score(y_train, y_pred),
        "precision": precision_score(y_train, y_pred),
        "recall": recall_score(y_train, y_pred),
        "f1": f1_score(y_train, y_pred)
    })

In [80]:
best_cv_threshold = max(cv_threshold_results,key=lambda x: x["f1"])
best_cv_threshold

{'threshold': np.float64(0.35),
 'accuracy': 0.8565,
 'precision': 0.6673611111111111,
 'recall': 0.5895705521472393,
 'f1': 0.6260586319218241}

In [82]:
best_threshold = 0.35
gb_model.fit(X_train_tree, y_train)
y_prob_test = gb_model.predict_proba(X_test_tree)[:, 1]
y_pred_final = (y_prob_test >= best_threshold).astype(int)
print("Accuracy:", accuracy_score(y_test, y_pred_final))
print("\nConfusion Matrix:")
print(confusion_matrix(y_test, y_pred_final))
print("\nClassification Report:")
print(classification_report(y_test, y_pred_final))

Accuracy: 0.8565

Confusion Matrix:
[[1468  125]
 [ 162  245]]

Classification Report:
              precision    recall  f1-score   support

           0       0.90      0.92      0.91      1593
           1       0.66      0.60      0.63       407

    accuracy                           0.86      2000
   macro avg       0.78      0.76      0.77      2000
weighted avg       0.85      0.86      0.85      2000

In [84]:
import joblib

In [86]:
joblib.dump(tree_preprocessor, "../models/preprocessor.pkl")
joblib.dump(gb_model, "../models/gradient_boosting_model.pkl")
joblib.dump(best_threshold, "../models/threshold.pkl")

['threshold.pkl']